// GENERATED by blockland/tools/gen_habitat_data.py — 手編集禁止。
// 正準ソース: blockland/docs/drafts/biome_params_draft.md §2 / §3.2 / §3.3
// 再生成: python3 blockland/tools/gen_habitat_data.py
// species=53 biomes=62 zones=30
export const HABITAT = {
 "roam": {
  "TRN": 0,
  "DPO": 0,
  "DEP": 1,
  "SHF": 0,
  "OCN": 0,
  "MNG": 3,
  "BCH": 2,
  "TWN": 0,
  "WET": 4,
  "PLN": 4,
  "JGL": 5,
  "PLR": 1,
  "MDW": 5,
  "FOR": 4,
  "DSR": 1,
  "SAV": 3,
  "SNW": 1,
  "SHR": 3,
  "DRF": 4,
  "TND": 2,
  "STP": 2,
  "THN": 1,
  "WDH": 4,
  "ICE": 1,
  "TGA": 3,
  "PLT": 2,
  "DRU": 3,
  "CTG": 2,
  "MJG": 4,
  "MSA": 1,
  "DPL": 2,
  "CDS": 1,
  "SVH": 2,
  "MFR": 3,
  "RPL": 1,
  "MOR": 2,
  "IFD": 1,
  "HST": 2,
  "RFM": 4,
  "SUB": 2,
  "HDS": 1,
  "VOL": 1,
  "SST": 1,
  "MTN": 2,
  "GLC": 1,
  "CLF": 3,
  "CDM": 1,
  "ALG": 2,
  "ARK": 1,
  "ALT": 1,
  "CDH": 1,
  "SNM": 1,
  "IDM": 0,
  "SLT": 1,
  "HRK": 1,
  "AFF": 1,
  "CHL": 1,
  "HGL": 1,
  "HMT": 1,
  "PSN": 0,
  "XPK": 0,
  "HIM": 0
 },
 "zones": [
  "NEW",
  "NEE",
  "PAN",
  "CAR",
  "AMZ",
  "AND",
  "CHC",
  "PAT",
  "AFW",
  "AFE",
  "AFS",
  "MDG",
  "SAH",
  "ARB",
  "EUR",
  "MED",
  "SIB",
  "CAS",
  "SIN",
  "JPN",
  "ISU",
  "IIC",
  "SUN",
  "WLC",
  "AUS",
  "NGU",
  "NZL",
  "PAC",
  "ARC",
  "ANT"
 ],
 "species": [
  {
   "name": "アザラシ",
   "biomes": [
    "BCH",
    "GLC",
    "HGL",
    "ICE",
    "IFD",
    "SNW"
   ],
   "zones": [
    "ANT",
    "ARC",
    "EUR",
    "MED",
    "NEE",
    "NEW",
    "SIB",
    "SIN"
   ]
  },
  {
   "name": "アルパカ",
   "biomes": [
    "ALG",
    "ARK",
    "CDM",
    "CHL",
    "DPL",
    "HMT",
    "MTN",
    "SNM"
   ],
   "zones": [
    "AND",
    "PAT"
   ]
  },
  {
   "name": "イヌ",
   "biomes": [
    "MDW",
    "PLN",
    "SAV",
    "SHR",
    "STP",
    "SVH"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "AMZ",
    "AND",
    "ARB",
    "AUS",
    "CAS",
    "CHC",
    "EUR",
    "ISU",
    "MDG",
    "MED",
    "NEE",
    "NEW",
    "NZL",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "SUN"
   ]
  },
  {
   "name": "イノシシ",
   "biomes": [
    "ALG",
    "ARK",
    "FOR",
    "MFR",
    "MTN",
    "SAV",
    "SVH",
    "WDH"
   ],
   "zones": [
    "ARB",
    "CAS",
    "EUR",
    "IIC",
    "ISU",
    "JPN",
    "MED",
    "SIB",
    "SIN",
    "SUN"
   ]
  },
  {
   "name": "インコ",
   "biomes": [
    "CLF",
    "DRF",
    "DRU",
    "JGL",
    "MJG",
    "RFM"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "AMZ",
    "AND",
    "AUS",
    "CAR",
    "CHC",
    "IIC",
    "ISU",
    "MDG",
    "NGU",
    "PAC",
    "PAN",
    "SUN",
    "WLC"
   ]
  },
  {
   "name": "ウサギ",
   "biomes": [
    "AFF",
    "ALT",
    "CDS",
    "CHL",
    "DPL",
    "FOR",
    "IFD",
    "MDW",
    "MFR",
    "PLN",
    "PLR",
    "SHR",
    "SNW",
    "SST",
    "STP",
    "TND",
    "WDH"
   ],
   "zones": [
    "ARB",
    "AUS",
    "CAS",
    "EUR",
    "ISU",
    "JPN",
    "MED",
    "NEE",
    "NEW",
    "SAH",
    "SIB",
    "SIN"
   ]
  },
  {
   "name": "ウシ",
   "biomes": [
    "MDW",
    "PLN",
    "SAV",
    "SHR",
    "STP",
    "SVH"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "AMZ",
    "AND",
    "ARB",
    "AUS",
    "CAS",
    "CHC",
    "EUR",
    "ISU",
    "MDG",
    "MED",
    "NEE",
    "NEW",
    "NZL",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "SUN"
   ]
  },
  {
   "name": "ウマ",
   "biomes": [
    "ALG",
    "ARK",
    "HST",
    "MTN",
    "PLN",
    "PLT",
    "SAV",
    "SHR",
    "STP",
    "SVH"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "AMZ",
    "AND",
    "ARB",
    "AUS",
    "CAS",
    "CHC",
    "EUR",
    "IIC",
    "ISU",
    "MDG",
    "MED",
    "NEE",
    "NEW",
    "NGU",
    "NZL",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "SUN",
    "WLC"
   ]
  },
  {
   "name": "オオカミ",
   "biomes": [
    "ALT",
    "CTG",
    "FOR",
    "IFD",
    "MFR",
    "PLR",
    "SNW",
    "TGA",
    "TND",
    "WDH"
   ],
   "zones": [
    "ARB",
    "ARC",
    "CAS",
    "EUR",
    "ISU",
    "JPN",
    "MED",
    "NEE",
    "NEW",
    "SIB",
    "SIN"
   ]
  },
  {
   "name": "カエル",
   "biomes": [
    "DRF",
    "FOR",
    "JGL",
    "MFR",
    "MNG",
    "MOR",
    "WDH",
    "WET"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "AMZ",
    "AND",
    "ARB",
    "AUS",
    "CAR",
    "CAS",
    "CHC",
    "EUR",
    "IIC",
    "ISU",
    "JPN",
    "MDG",
    "MED",
    "NEE",
    "NEW",
    "NGU",
    "NZL",
    "PAC",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "SUN",
    "WLC"
   ]
  },
  {
   "name": "カバ",
   "biomes": [
    "DRF",
    "JGL",
    "MNG",
    "MOR",
    "SAV",
    "SVH",
    "WET"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW"
   ]
  },
  {
   "name": "カモメ",
   "biomes": [
    "BCH"
   ],
   "zones": [
    "AFE",
    "AFW",
    "AMZ",
    "AND",
    "ARB",
    "ARC",
    "AUS",
    "CHC",
    "EUR",
    "IIC",
    "ISU",
    "MED",
    "NEE",
    "NEW",
    "NGU",
    "NZL",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "SUN",
    "WLC"
   ]
  },
  {
   "name": "カワウソ",
   "biomes": [
    "BCH",
    "FOR",
    "MFR",
    "MNG",
    "MOR",
    "WDH",
    "WET"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "AMZ",
    "AND",
    "CAS",
    "EUR",
    "IIC",
    "ISU",
    "JPN",
    "MED",
    "NEE",
    "NEW",
    "SIB",
    "SIN",
    "SUN"
   ]
  },
  {
   "name": "カンガルー",
   "biomes": [
    "DPL",
    "DSR",
    "SAV",
    "THN"
   ],
   "zones": [
    "AUS"
   ]
  },
  {
   "name": "キツネ",
   "biomes": [
    "ALG",
    "ALT",
    "ARK",
    "CDH",
    "CDM",
    "CDS",
    "CTG",
    "DPL",
    "FOR",
    "IFD",
    "MFR",
    "MTN",
    "PLR",
    "SNW",
    "TGA",
    "TND",
    "WDH"
   ],
   "zones": [
    "ARB",
    "ARC",
    "CAS",
    "EUR",
    "ISU",
    "JPN",
    "MED",
    "NEE",
    "NEW",
    "SAH",
    "SIB",
    "SIN"
   ]
  },
  {
   "name": "キリン",
   "biomes": [
    "SAV",
    "SVH"
   ],
   "zones": [
    "AFE",
    "AFS"
   ]
  },
  {
   "name": "クジャク",
   "biomes": [
    "CLF",
    "DRF",
    "DRU",
    "JGL",
    "MJG",
    "RFM"
   ],
   "zones": [
    "IIC",
    "ISU"
   ]
  },
  {
   "name": "クマ(ホッキョクグマ統合)",
   "biomes": [
    "ALG",
    "ALT",
    "ARK",
    "CTG",
    "FOR",
    "GLC",
    "HGL",
    "ICE",
    "IFD",
    "MFR",
    "MTN",
    "PLR",
    "SNW",
    "SUB",
    "TGA",
    "TND",
    "WDH"
   ],
   "zones": [
    "ARC",
    "CAS",
    "EUR",
    "IIC",
    "ISU",
    "JPN",
    "MED",
    "NEE",
    "NEW",
    "SIB",
    "SIN"
   ]
  },
  {
   "name": "コブラ",
   "biomes": [
    "DEP",
    "DSR",
    "HDS",
    "RPL",
    "SAV",
    "SVH",
    "THN"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "ARB",
    "ISU",
    "SAH",
    "SIN",
    "SUN"
   ]
  },
  {
   "name": "ゴリラ",
   "biomes": [
    "DRF",
    "DRU",
    "JGL",
    "MJG",
    "RFM"
   ],
   "zones": [
    "AFW"
   ]
  },
  {
   "name": "サル",
   "biomes": [
    "CLF",
    "DRF",
    "DRU",
    "FOR",
    "JGL",
    "MFR",
    "MJG",
    "RFM",
    "WDH"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "AMZ",
    "AND",
    "CAR",
    "CHC",
    "IIC",
    "ISU",
    "JPN",
    "MDG",
    "PAN",
    "SIN",
    "SUN",
    "WLC"
   ]
  },
  {
   "name": "シカ",
   "biomes": [
    "CTG",
    "FOR",
    "MDW",
    "MFR",
    "PLN",
    "SHR",
    "STP",
    "SUB",
    "TGA",
    "WDH"
   ],
   "zones": [
    "AND",
    "CAS",
    "EUR",
    "JPN",
    "MED",
    "NEE",
    "NEW",
    "SIB",
    "SIN"
   ]
  },
  {
   "name": "シマウマ",
   "biomes": [
    "ALG",
    "ARK",
    "MTN",
    "SAV",
    "SVH"
   ],
   "zones": [
    "AFE",
    "AFS"
   ]
  },
  {
   "name": "スズメ",
   "biomes": [
    "FOR",
    "MDW",
    "MFR",
    "PLN",
    "SHR",
    "STP",
    "WDH"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AND",
    "ARB",
    "AUS",
    "CAR",
    "CAS",
    "CHC",
    "EUR",
    "IIC",
    "ISU",
    "JPN",
    "MED",
    "NEE",
    "NEW",
    "NZL",
    "PAC",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "WLC"
   ]
  },
  {
   "name": "ゾウ",
   "biomes": [
    "DRF",
    "JGL",
    "SAV",
    "SVH"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "IIC",
    "ISU",
    "SUN"
   ]
  },
  {
   "name": "タカ",
   "biomes": [
    "AFF",
    "ALG",
    "ARK",
    "CHL",
    "HMT",
    "HRK",
    "MSA",
    "MTN",
    "RPL",
    "SAV",
    "SNM",
    "SVH"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "AMZ",
    "AND",
    "ARB",
    "AUS",
    "CAS",
    "CHC",
    "EUR",
    "IIC",
    "ISU",
    "MDG",
    "MED",
    "NEE",
    "NEW",
    "NGU",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "SUN",
    "WLC"
   ]
  },
  {
   "name": "タヌキ",
   "biomes": [
    "FOR",
    "MFR",
    "PLN",
    "SHR",
    "STP",
    "WDH"
   ],
   "zones": [
    "EUR",
    "JPN",
    "SIB",
    "SIN"
   ]
  },
  {
   "name": "ダチョウ",
   "biomes": [
    "DEP",
    "DSR",
    "SAV",
    "SVH",
    "THN"
   ],
   "zones": [
    "AFE",
    "AFS",
    "ARB",
    "SAH"
   ]
  },
  {
   "name": "ツル",
   "biomes": [
    "MNG",
    "MOR",
    "PLN",
    "SAV",
    "SHR",
    "STP",
    "SVH",
    "WET"
   ],
   "zones": [
    "AFE",
    "AFS",
    "CAS",
    "EUR",
    "IIC",
    "ISU",
    "MED",
    "NEE",
    "NEW",
    "SIB",
    "SIN"
   ]
  },
  {
   "name": "トカゲ",
   "biomes": [
    "ALG",
    "ARK",
    "DEP",
    "DSR",
    "HDS",
    "MSA",
    "MTN",
    "RPL",
    "THN",
    "VOL"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "AMZ",
    "AND",
    "ARB",
    "AUS",
    "CAR",
    "CAS",
    "CHC",
    "EUR",
    "IIC",
    "ISU",
    "JPN",
    "MDG",
    "MED",
    "NEE",
    "NEW",
    "NGU",
    "NZL",
    "PAC",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "SUN",
    "WLC"
   ]
  },
  {
   "name": "トナカイ",
   "biomes": [
    "ALT",
    "CTG",
    "IFD",
    "PLR",
    "SNW",
    "TGA",
    "TND"
   ],
   "zones": [
    "ARC",
    "EUR",
    "NEE",
    "NEW",
    "SIB"
   ]
  },
  {
   "name": "トラ",
   "biomes": [
    "CLF",
    "DRF",
    "DRU",
    "FOR",
    "JGL",
    "MFR",
    "MJG",
    "RFM",
    "WDH"
   ],
   "zones": [
    "IIC",
    "ISU",
    "SIB",
    "SIN",
    "SUN"
   ]
  },
  {
   "name": "ナマケモノ",
   "biomes": [
    "CLF",
    "DRF",
    "DRU",
    "JGL",
    "MJG",
    "RFM"
   ],
   "zones": [
    "AMZ",
    "PAN"
   ]
  },
  {
   "name": "ニワトリ",
   "biomes": [
    "MDW",
    "PLN",
    "SAV",
    "SHR",
    "STP",
    "SVH"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "AMZ",
    "AND",
    "ARB",
    "AUS",
    "CAS",
    "CHC",
    "EUR",
    "ISU",
    "MDG",
    "MED",
    "NEE",
    "NEW",
    "NZL",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "SUN"
   ]
  },
  {
   "name": "ネコ",
   "biomes": [
    "FOR",
    "MDW",
    "MFR",
    "PLN",
    "SHR",
    "STP",
    "WDH"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AND",
    "ARB",
    "AUS",
    "CAR",
    "CAS",
    "CHC",
    "EUR",
    "IIC",
    "ISU",
    "JPN",
    "MED",
    "NEE",
    "NEW",
    "NZL",
    "PAC",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "WLC"
   ]
  },
  {
   "name": "ネズミ",
   "biomes": [
    "AFF",
    "CDH",
    "CDM",
    "CDS",
    "CHL",
    "DEP",
    "DPL",
    "DSR",
    "FOR",
    "HDS",
    "MDW",
    "MFR",
    "PLN",
    "SHR",
    "SST",
    "STP",
    "THN",
    "VOL",
    "WDH"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "AMZ",
    "AND",
    "ARB",
    "AUS",
    "CAR",
    "CAS",
    "CHC",
    "EUR",
    "IIC",
    "ISU",
    "JPN",
    "MDG",
    "MED",
    "NEE",
    "NEW",
    "NGU",
    "NZL",
    "PAC",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "SUN",
    "WLC"
   ]
  },
  {
   "name": "ハト",
   "biomes": [
    "FOR",
    "MDW",
    "MFR",
    "PLN",
    "SHR",
    "STP",
    "WDH"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AND",
    "ARB",
    "AUS",
    "CAR",
    "CAS",
    "CHC",
    "EUR",
    "IIC",
    "ISU",
    "JPN",
    "MED",
    "NEE",
    "NEW",
    "NZL",
    "PAC",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "WLC"
   ]
  },
  {
   "name": "ハリネズミ",
   "biomes": [
    "ALG",
    "ARK",
    "FOR",
    "MFR",
    "MTN",
    "PLN",
    "SHR",
    "STP",
    "WDH"
   ],
   "zones": [
    "AFE",
    "AFS",
    "CAS",
    "EUR",
    "MED",
    "SIB",
    "SIN"
   ]
  },
  {
   "name": "ヒツジ",
   "biomes": [
    "AFF",
    "ALG",
    "ARK",
    "CDH",
    "CDM",
    "CDS",
    "CHL",
    "DPL",
    "HST",
    "MDW",
    "MTN",
    "PLN",
    "PLT",
    "SHR",
    "SST",
    "STP"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "AMZ",
    "AND",
    "ARB",
    "AUS",
    "CAS",
    "CHC",
    "EUR",
    "IIC",
    "ISU",
    "MDG",
    "MED",
    "NEE",
    "NEW",
    "NGU",
    "NZL",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "WLC"
   ]
  },
  {
   "name": "ビーバー",
   "biomes": [
    "BCH",
    "FOR",
    "MFR",
    "MNG",
    "MOR",
    "WDH",
    "WET"
   ],
   "zones": [
    "EUR",
    "NEE",
    "NEW",
    "SIB"
   ]
  },
  {
   "name": "フェネック",
   "biomes": [
    "DEP",
    "DSR",
    "THN"
   ],
   "zones": [
    "SAH"
   ]
  },
  {
   "name": "フクロウ",
   "biomes": [
    "ALT",
    "CTG",
    "FOR",
    "IFD",
    "MFR",
    "PLR",
    "SNW",
    "SUB",
    "TGA",
    "TND",
    "WDH"
   ],
   "zones": [
    "AFE",
    "ARB",
    "ARC",
    "AUS",
    "CAR",
    "CAS",
    "EUR",
    "IIC",
    "ISU",
    "JPN",
    "MED",
    "NEE",
    "NEW",
    "NGU",
    "NZL",
    "PAC",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "WLC"
   ]
  },
  {
   "name": "フラミンゴ",
   "biomes": [
    "BCH",
    "MNG",
    "MOR",
    "SAV",
    "SVH",
    "WET"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AND",
    "ARB",
    "CAR",
    "CHC",
    "MED",
    "PAN",
    "PAT",
    "SAH"
   ]
  },
  {
   "name": "ブタ",
   "biomes": [
    "FOR",
    "MDW",
    "MFR",
    "PLN",
    "SHR",
    "STP",
    "WDH"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AND",
    "ARB",
    "AUS",
    "CAR",
    "CAS",
    "CHC",
    "EUR",
    "IIC",
    "ISU",
    "JPN",
    "MED",
    "NEE",
    "NEW",
    "NZL",
    "PAC",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "WLC"
   ]
  },
  {
   "name": "ヘビ",
   "biomes": [
    "CLF",
    "DEP",
    "DRF",
    "DRU",
    "DSR",
    "JGL",
    "MJG",
    "RFM",
    "SAV",
    "SVH",
    "THN"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "AMZ",
    "AND",
    "ARB",
    "AUS",
    "CAR",
    "CAS",
    "CHC",
    "IIC",
    "ISU",
    "JPN",
    "MDG",
    "MED",
    "NEE",
    "NEW",
    "NGU",
    "PAC",
    "PAN",
    "SAH",
    "SIN",
    "SUN",
    "WLC"
   ]
  },
  {
   "name": "ペンギン",
   "biomes": [
    "BCH",
    "GLC",
    "HGL",
    "ICE",
    "SNW"
   ],
   "zones": [
    "AND",
    "ANT",
    "AUS",
    "NZL",
    "PAT"
   ]
  },
  {
   "name": "ヤギ",
   "biomes": [
    "AFF",
    "ALG",
    "ALT",
    "ARK",
    "CDH",
    "CDM",
    "CDS",
    "CHL",
    "CTG",
    "DPL",
    "HMT",
    "MTN",
    "PLR",
    "SNM",
    "SST",
    "SUB",
    "TGA",
    "TND"
   ],
   "zones": [
    "ARB",
    "CAS",
    "EUR",
    "ISU",
    "MED",
    "NEW",
    "SIB",
    "SIN"
   ]
  },
  {
   "name": "ライオン",
   "biomes": [
    "SAV",
    "SVH"
   ],
   "zones": [
    "AFE",
    "AFS"
   ]
  },
  {
   "name": "ラクダ",
   "biomes": [
    "CDH",
    "CDM",
    "CDS",
    "DEP",
    "DSR",
    "HDS",
    "RPL",
    "THN"
   ],
   "zones": [
    "ARB",
    "CAS",
    "SAH"
   ]
  },
  {
   "name": "リス",
   "biomes": [
    "CLF",
    "CTG",
    "DRF",
    "DRU",
    "FOR",
    "JGL",
    "MFR",
    "MJG",
    "RFM",
    "TGA",
    "WDH"
   ],
   "zones": [
    "AMZ",
    "AND",
    "CAS",
    "EUR",
    "IIC",
    "ISU",
    "JPN",
    "MED",
    "NEE",
    "NEW",
    "PAN",
    "SIB",
    "SIN",
    "SUN"
   ]
  },
  {
   "name": "ロバ",
   "biomes": [
    "ALG",
    "ARK",
    "CDH",
    "CDM",
    "CDS",
    "CHL",
    "DPL",
    "MTN",
    "PLN",
    "PLT",
    "SAV",
    "SHR",
    "STP",
    "SVH"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "AMZ",
    "AND",
    "ARB",
    "AUS",
    "CAS",
    "CHC",
    "EUR",
    "IIC",
    "ISU",
    "MDG",
    "MED",
    "NEE",
    "NEW",
    "NGU",
    "NZL",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "SUN",
    "WLC"
   ]
  },
  {
   "name": "ワシ",
   "biomes": [
    "AFF",
    "ALG",
    "ARK",
    "CHL",
    "GLC",
    "HGL",
    "HMT",
    "HRK",
    "ICE",
    "IFD",
    "MSA",
    "MTN",
    "RPL",
    "SNM",
    "SNW",
    "VOL"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "AMZ",
    "AND",
    "ARB",
    "ARC",
    "AUS",
    "CAR",
    "CAS",
    "CHC",
    "EUR",
    "IIC",
    "ISU",
    "JPN",
    "MDG",
    "MED",
    "NEW",
    "NGU",
    "NZL",
    "PAC",
    "PAN",
    "PAT",
    "SAH",
    "SIB",
    "SIN",
    "SUN",
    "WLC"
   ]
  },
  {
   "name": "ワニ",
   "biomes": [
    "DRF",
    "JGL",
    "MNG",
    "MOR",
    "SAV",
    "SVH",
    "WET"
   ],
   "zones": [
    "AFE",
    "AFS",
    "AFW",
    "AMZ",
    "AUS",
    "CAR",
    "IIC",
    "ISU",
    "NEE",
    "NGU",
    "PAN",
    "SUN",
    "WLC"
   ]
  }
 ]
};
